### ISSUE TITLE
A better readme

### ISSUE THREAD

**Issue by aescaffre** [mzabriskie/pdf-annotate.js#1]
Hi,

Nuxeo Platform makes use of pdf.js for the viewer and we are currently looking for adding annotation support to our viewer. Would it be possible that you develop a little bit more your readme to expose your objectives and current status, and write down a way to test what you have already done. Maybe then we could evaluate and maybe fork to help within next months. Thank you !

**Comment by aescaffre** [comment]
I was able to build and try samples with npm. Anyway still interested in your goals!

**Comment by mzabriskie** [comment]
There's a bit more to the README now. I will fill out more documentation soon, but at least you can see some examples and objectives with the lib.
