### ISSUE TITLE
UI.renderPage not documented

### ISSUE THREAD

**Issue by aaronshaf** [mzabriskie/pdf-annotate.js#12]
It seems `PDFJSAnnotate.render` is where metadata is set, but `PDFJSAnnotate.UI.renderPage` is what the main example is using, which does not in turn use `PDFJSAnnotate.render`. UI.renderPage however is [not documented](https://github.com/mzabriskie/pdf-annotate.js/blob/master/docs/api/UI.md).

**Comment by mzabriskie** [comment]
`UI.renderPage` does indeed use `PDFJSAnnotate.render` https://github.com/mzabriskie/pdf-annotate.js/blob/master/src/UI/page.js#L70

Though you are correct that the docs are missing. Will update.

**Comment by mzabriskie** [comment]
Docs are updated https://github.com/mzabriskie/pdf-annotate.js/blob/master/docs/api/UI.md#createpage
