### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by ckuetbach** [mzabriskie/pdf-annotate.js#4]
I did not find any license in this repository. I would like to use some of this code, but I need to know, if I am allowed to do this in a commercial software.

**Comment by ingorammer** [comment]
This would also be very interesting for us ...

**Comment by jprberlin** [comment]
As stated in the package file its MIT: https://github.com/mzabriskie/pdf-annotate.js/blob/master/package.json

**Comment by mzabriskie** [comment]
Confirmed that this library is licensed under MIT.
