### ISSUE TITLE
importing best practice

### ISSUE THREAD

**Issue by mvanlonden** [mzabriskie/pdf-annotate.js#9]
would we import the library by importing from the dist folder?
`import PDFJSAnnotate from 'pdf-annotate.js/dist/pdf-annotate'`

because the package file specifies `index.js` as main
`index.js` points to `src/PDFJSAnnotate`

**Comment by mzabriskie** [comment]
I have changed the package.json to have main point to `dist/pdf-annotate.js` which will provide you with a UMD bundle of the library.
